name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    run-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
     - run: docker build -t bengoren/react-test -f ./client/Dockerfile.dev ./client
     - run: docker run -e CI=true bengoren/react-test npm test

     - run: docker build -t bengoren/multi-client ./client
     - run: docker build -t bengoren/multi-nginx ./nginx
     - run: docker build -t bengoren/multi-server ./server
     - run: docker build -t bengoren/multi-worker ./worker

     - run: docker push bengoren/multi-client
     - run: docker push bengoren/multi-nginx
     - run: docker push bengoren/multi-server
     - run: docker push bengoren/multi-worker